
/* 
 * This file is auto-generated by the cmake of 
 * the extension plugin.
 */
 
/*******************************************************************************
  Copyright (C) 2010,2011 Mickael Gadroy, University of Reims Champagne-Ardenne (Fr)
                          Project managers: Eric Henon and Michael Krajecki
                          Financial support: Region Champagne-Ardenne (Fr)

  This file is part of WmAvo (WiiChem project)
  WmAvo - Integrate the Wiimote and the Nunchuk in Avogadro software for the
  handling of the atoms and the camera.
  For more informations, see the README file.

  WmAvo is free software; you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation; either version 3 of the License, or
  (at your option) any later version.

  WmAvo is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with WmAvo. If not, see <http://www.gnu.org/licenses/>.
*******************************************************************************/

#ifndef __REVISION_H__
#define __REVISION_H__

#define AVOGADRO_VERSION_MAJOR 1
#define AVOGADRO_VERSION_MINOR 1
#define AVOGADRO_VERSION_PATCH 0

#define WMAVO_VERSION_MAJOR 2
#define WMAVO_VERSION_MINOR 0
#define WMAVO_VERSION_PATCH 0

#define AVO_VERSION_ABOVE_1_0_1 if( AVOGADRO_VERSION_MAJOR == 0 ) 0 ; \
                                else if( AVOGADRO_VERSION_MAJOR>=1 && AVOGADRO_VERSION_MINOR>=0 && AVOGADRO_VERSION_PATCH<=1 ) 0 ; \
                                else if( AVOGADRO_VERSION_MAJOR>=1 && AVOGADRO_VERSION_MINOR>=0 && AVOGADRO_VERSION_PATCH>1 ) 1 ; \
                                else if( AVOGADRO_VERSION_MAJOR>=2 ) 1 ;
                                
#endif
