######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 20 23:49:44 2006
######################################################################
QMAKE_LFLAGS += -rdynamic

TEMPLATE = subdirs
SUBDIRS = engines tools avogadro.pro

