.Dd March 15, 2010
.Os "Avogadro" 1.1
.Sh NAME
.Nm avogadro
.Nd "Advanced molecular editor"
.Sh SYNOPSIS
.Nm
.Ar filename
.Sh DESCRIPTION
Avogadro is an advanced molecular editor designed for cross-platform use 
in computational chemistry, molecular modeling, bioinformatics, materials 
science, and related areas. It offers flexible rendering and a powerful 
plugin architecture.
.Sh EXAMPLES
.Bl -tag -width flag
.It Nm Ar filename
.El
Open chemical file filename
.Sh SEE ALSO
.Xr avopkg 1 .
.br
For more information about Avogadro, see 
\%<\fBhttp://avogadro.openmolecules.net/\fR>
.Pp
Avogadro is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.Pp
Avogadro is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.