FIND_PATH(OPENBABEL_INCLUDE_DIR openbabel/mol.h 
	/usr/include
	/usr/local/include
	/usr/include/openbabel-2.0 
	/usr/local/include/openbabel-2.0
)

FIND_LIBRARY(OPENBABEL_LIBRARY 
	NAMES 
		openbabel 
	PATH 
		/usr/lib 
		/usr/local/lib
) 

IF (OPENBABEL_LIBRARY AND OPENBABEL_INCLUDE_DIR)
	SET(OPENBABEL_LIBRARIES ${OPENBABEL_LIBRARY})
	SET(OPENBABEL_FOUND TRUE)
ENDIF (OPENBABEL_LIBRARY AND OPENBABEL_INCLUDE_DIR)


IF (OPENBABEL_FOUND)
	IF (NOT OPENBABEL_FIND_QUIETLY)
		MESSAGE(STATUS "Found OpenBabel: ${OPENBABEL_LIBRARY}")
	ENDIF (NOT OPENBABEL_FIND_QUIETLY)
ELSE (OPENBABEL_FOUND)
	IF (OPENBABEL_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find OpenBabel")
	ENDIF (OPENBABEL_FIND_REQUIRED)
ENDIF (OPENBABEL_FOUND)
