######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 1 01:37:27 2010
######################################################################

TEMPLATE = app
TARGET = qperiodictable
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += avogadro
LIBS += -lperiodictable -Wl,-rpath,/usr/local/lib

# Input
HEADERS += qperiodictable.h
SOURCES += qperiodictable.cpp
