######################################################################
# Automatically generated by qmake (2.00a) Fri Apr 28 04:18:28 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl
CONFIG += link_pkgconfig 
PKGCONFIG += openbabel-2.0

# Input
HEADERS += AMainWindow.h AGLWidget.h defines.h
SOURCES += AMainWindow.cpp AGLWidget.cpp main.cpp
