######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 20 23:49:44 2006
######################################################################

TEMPLATE = subdirs
SUBDIRS = engines avogadro.pro
