/**********************************************************************
  HelloWorldExtension

  Copyright (C) 2010 David C. Lonie

  This library is free software; you can redistribute it and/or modify
  it under the terms of the GNU Library General Public License as
  published by the Free Software Foundation; either version 2.1 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
 ***********************************************************************/

#include "helloworlddialog.h"

namespace HelloWorld {

  HelloWorldDialog::HelloWorldDialog(QWidget *parent, Qt::WindowFlags f ) :
    QDialog( parent, f )
  {
    // This initializes the ui member function to contain pointers to
    // all GUI elements in the helloworlddialog.ui file
    ui.setupUi(this);

    // This connection will hide the dialog when the hide button is
    // clicked
    connect(ui.push_hide, SIGNAL(clicked()),
            this, SLOT(hide()));
  }

}

// This includes the files generated by Qt's moc at compile time to
// ensure that signals/slots work. If you ever see errors about
// missing vtables with gcc, check that you haven't forgotten one of
// these:
#include "helloworlddialog.moc"
